### ISSUE TITLE
Version question concerning docker swarm and vxlan plugin

### ISSUE THREAD

**Issue by krigbaum** [clinta/docker-vxlan-plugin#1]
We have been attempting to implement the docker-vxlan-plugin in docker 1.12 and have been running into some problems I'm hoping you can help clear up.

The tutorial for your plug-in uses pre-1.12 style swarms so I  followed those instructions in our first attempt to implement the plug-in.  It seemed to go okay until I hit the instruction in the tutorial "docker run -d --name=swarm-master-nginx --net=vxlan42 -e constraint:node==swarm-master nginx" and no matter what we tried, we kept getting "endpoint not found errors".

We decided that it could possibly be a problem trying to use the pre-1.12 style swarms in 1.12.  I recreated everything and verified the swarm was working as expected.  We started hitting a problem on the previous tutorial instruction to create the xvlan network.  The exact instruction we used for our environment was from the tutorial "docker network create -d vxlan -o Group=239.1.1.1 -o VxlanId=42 -o VtepDev=eno1 --subnet=192.168.0.0/24 --gateway=192.168.0.254 vxnet." which gave us 'rpc error: code = 3 desc = invalid driver specified".  Again I tried to use a few work-arounds, but keep hitting a wall/

Has the docker-vxlan-plugin been tested on 1.12?  Is there any reason it should not work as described?  Do you have any new instructions for the tutorial based on docker 1.12?  Do you see any other potential solutions we can investigate?

Thank you.
Larry Krigbaum

**Comment by clinta** [comment]
It does not work in swarm mode in 1.12. I've not tested trying to use the old style swarm with Docker 1.12. Since docker dropped support for global network plugins with swarm mode, I've only been running in local mode.

Since the old style swarm clustering is no longer actively developed, I haven't done any testing with it since 1.12 was released, and will probably be removing the global mode support.

**Comment by hervenicol** [comment]
I can tell you it works in "old style" swarm with docker 1.12.
Before dropping global mode support, please note that "old style" swarm seems to be still maintained, as 1.2.6 was released on 2017-01-17.


Having said that, it's rather sad it does not work with "new swarm mode".
Do you have an advice for vxlans with new swarm mode ?


Whatever happens to this plugin, thanks for your work on it @clinta . It has been very useful to me.

**Comment by clinta** [comment]
Good to know that there's still some work being done on the old style swarm. I won't bother removing global mode support as long as that is not officially abandoned.

https://docs.docker.com/engine/extend/plugins_network/#/network-driver-plugins-and-swarm-mode

> Docker Engine running in swarm mode currently only supports the built-in overlay driver for networking.


Unless/until that changes, there's not much hope for vxlans with swarm mode.

**Comment by hervenicol** [comment]
Thanks @clinta for the explanations.

The current status of swarm mode and network plugins is quite unclear.
I have found this: https://github.com/docker/docker/issues/24569#issuecomment-267044175 saying that "1.13 supports network plugins with swarm-mode"

So I suspect the doc is outdated.
